# ------------------------------------------------------------------------
# PowerBEV
# Copyright (c) 2023 Peizheng Li. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from FIERY (https://github.com/wayveai/fiery)
# Copyright (c) 2021 Wayve Technologies Limited. All Rights Reserved.
#--config powerbev/configs/powerbev-2-100.yml DATASET.DATAROOT /mnt/data/wzc/carla-1029/ LOG_DIR /root/PowerBEV/dir_2_100/ GPUS [0,1,2,3] BATCHSIZE 4
# ------------------------------------------------------------------------

TAG: 'dhd'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 1
PRECISION: 16


LIFT:
  # Long
  X_BOUND: [-50.0, 50.0, 0.5]  # Forward
  Y_BOUND: [-50.0, 50.0, 0.5]  # Sides
  D_BOUND: [0.0, 10.0, 0.1]
  Z_BOUND: [-60.0, -40.0, 20.0]
IMAGE:
  NAMES : ['UAV_1_1', 'UAV_1_2', 'UAV_1_3', 'UAV_2']
  # # Short
  # X_BOUND: [-25.0, 25.0, 0.25]  # Forward
  # Y_BOUND: [-25.0, 25.0, 0.25]  # Sides

MODEL:
  BN_MOMENTUM: 0.05
  NAME: 'SISW'

OPTIMIZER:
  LR:
    3e-4

N_WORKERS: 2
VIS_INTERVAL: 100